package com.dojo.javapatterns.bridge.university.enums;

public enum CourseEnum {
    CALCULUS_I,
    CALCULUS_II,
    CALCULUS_III,
    ALGEBRA,
    LINEAR_ALGEBRA,
    GEOMETRY,
    DIFFERENTIAL_EQUATIONS,
    CLASSIC_PHYSICS,
    MODERN_PHYSICS,
    ORGANIC_CHEMISTRY,
    INORGANIC_CHEMISTRY,
    ELECTROMAGNETISM,
    INTRODUCTION_TO_COMPUTER_SCIENCE,
    COMPUTING_BASICS,
    ALGORITHMS,
    MECHANICS,
    ANALOG_CONTROL,
    DIGITAL_CONTROL,
    ANALOG_ELECTRONICS,
    DIGITAL_ELECTRONICS,
    MATERIAL_SCIENCE,
    ARTIFICIAL_INTELLIGENCE
}
